# Add 'branding' to any file changes within 'logos' folder
branding: logos/*

# Add 'repo' label to any root file changes
repo:
  - ./*

# Add 'enhancement' label to any change to source files
enhancement:
  - ./src/*
  - ./package.json
  - ./pakcage-lock.json
  - ./config.schema.json
  
# Add 'workflow' to any changes within 'workflow' folder or any subfolders
workflow:
  - .github/workflows/*
